FROM rust:1.88-slim

RUN apt-get update && apt-get install -y pkg-config libssl-dev && rm -rf /var/lib/apt/lists/*
RUN cargo install cargo-watch --version 8.5.2 --locked

WORKDIR /app
EXPOSE 8080
CMD ["cargo", "watch", "-x", "run"]
